name: release
on:
  push:
    tags:
      - "v*"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PETGPT_TOKEN }}

jobs:
  create-draft:
    runs-on: ubuntu-latest
    steps:
      - run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v3

      - run: |
          gh release create ${{github.ref_name}} -d -F CHANGELOG.md -t ${{github.ref_name}}
  windows:
    runs-on: windows-latest
    needs: create-draft
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: | 
          npm run build
          tar -zcvf ${{ env.VERSION }}.tar.gz -C release/${{ env.VERSION }}/win-unpacked .
        env:
          GITHUB_TOKEN: ${{ secrets.PETGPT_TOKEN }}
      - run: gh release upload ${{github.ref_name}} ${{ env.VERSION }}.tar.gz

  publish-release:
    runs-on: ubuntu-latest
    needs: [windows]
    steps:
      - uses: actions/checkout@v3
      - run: gh release edit ${{github.ref_name}} --draft=false